[package]
name = "raw-ptr-to-slice"
version = "0.1.0"
authors = ["guonaihong <guonaihong@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
